name: Build and Export IPA

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2' # Specify the Flutter version explicitly

    - name: Install CocoaPods
      run: sudo gem install cocoapods

    - name: Update CocoaPods repo
      run: pod repo update
      
    - name: Install dependencies
      run: flutter pub get

    - name: Install iOS dependencies
      run: |
        cd ios
        pod install
        cd ..

    - name: Build iOS app
      run: flutter build ios --no-codesign --release
      
    - name: Generate Manifest
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > manifest.plist
        echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> manifest.plist
        echo '<plist version="1.0">' >> manifest.plist
        echo '<dict>' >> manifest.plist
        echo '  <key>bundle-identifier</key>' >> manifest.plist
        echo '  <string>app.thedevs.ashur</string>' >> manifest.plist
        echo '  <key>version</key>' >> manifest.plist
        echo '  <string>1.0</string>' >> manifest.plist
        echo '  <key>url</key>' >> manifest.plist
        echo '  <string>https://itashur2.web.app/builds/ios.ipa</string>' >> manifest.plist
        echo '</dict>' >> manifest.plist
        echo '</plist>' >> manifest.plist
        
    - name: Upload IPA and Manifest
      uses: actions/upload-artifact@v2
      with:
        name: ipa-manifest
        path: |
          build/ios/ios.ipa
          manifest.plist
